---

- name: Manage and configure a borg server
  hosts: [ 'debops_service_borg_server' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.borg_server
      tags: [ 'role::borg_server' ]
